### ISSUE TITLE
Empty Editor field when special chars in code

### ISSUE THREAD

**Issue by instantflorian** [cwsoft/wbce-addon-file-editor#2]
The AFE fails to load the code of files if they include special characters like ä, ö, ß. Even if the Editarea is switched off the editor field stays empty. 
You can reproduce it under WBCE 1.x:
Set default charset to UTF-8 (default)
add_default_charset is off
Install f.ex. Anytopics 0.44 and try to edit include.php => empty file
If you add an special char in the file by using the AFE and save, the problem does not occur. Strange.

**Comment by cwsoft** [comment]
Hi Florian. Sounds like an error already reported in the WB forum some month ago. Can you please open the file causing issues with an editor like Notepad++ or Sublimetext and check the charset and search for any invalid characters? Bet there is a German Umlaut in a comment and the file is stored as ANSI instead of UTF8 wo BOM. Convert the file to UTF8 and relace the odd characters with umlaut again and it should work.

**Comment by instantflorian** [comment]
Well, yes, of course if I remove the character with an external tool, the file source code shows up. But thats not a fix for the bug I would say. It would be better if the AFE would not stop working in this case. There is not always the option of FTP file access and its frustrating to search for a wrong character in hundered lines of code.

**Comment by cwsoft** [comment]
Well the bug is that the file encoding was choosen to be ANSI, but an invalid character was used. Just follow PHP recommendation and store all textfiles to be treated by PHP as UTF8 without BOM. Than you can use all sorts of charavters like German Umlauts etc. without any issues. 

The bug is not related to AFE. Some background infos can be found here: http://forum.websitebaker.org/index.php/topic,24895.msg196321.html#msg196321
